version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: WebApi
      dockerfile: Dockerfile

  db:
    container_name: dev-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - PGDATA=/var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432