version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/WebApi/obj/
      - /app/WebApi/bin
    ports:
      - 8080:80
      - 8081:443
    command: ["dotnet", "watch", "run", "--project", "/app/WebApi/WebApi.csproj"]

  db:
    container_name: dev-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432