name: Build and Test API

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: cd api/WebApi && dotnet restore

    - name: Build
      run: dotnet build api/WebApi/WebApi.csproj --no-restore

    - name: Test
      run: dotnet test api/WebApi/WebApi.csproj --no-build --verbosity normal