services:
  WebApp:  
    image: Thingholm/hvad-skal-jeg-stemme:1.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: environment
    ports:
      - 5173:5173