services:
  WebApp:  
    image: Thingholm/hvad-skal-jeg-stemme:1.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: environment
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000